name: Testing the GitHub Pages publication

on:
  pull_request:
    branches:
      - gh-pages

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: remove files
      run: |
        rm -r -f -v  Gemfile.lock

    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
